### ISSUE TITLE
Perfdata line has one too many ; (semi-colons) per datasource

### ISSUE THREAD

**Issue by box293** [saj/pynagioscheck#2]
In the performance data that is output, each datasource has one too many semi-colons.

This:
```
cluster_nodes=2;;;;;
```
Should be:
```
cluster_nodes=2;;;;
```

Some programs discard the performance data because of the last semi-colon. 
The official nagios plugin development guidelines define performance data as:
https://nagios-plugins.org/doc/guidelines.html#AEN200
```
'label'=value[UOM];[warn];[crit];[min];[max]
```

You simply need to change line 295 from:
```
return ("%s=%s%s;%s;%s;%s;%s;" %
```
To:
```
return ("%s=%s%s;%s;%s;%s;%s" %
```

Keep up the great work!

Originally reported here:
https://support.nagios.com/forum/viewtopic.php?f=38&t=34984&p=162683#p162573

**Comment by saj** [comment]
Fixed by #3.
